[package]
name = "iroh-resolver"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of path resolution for iroh"

[dependencies]
anyhow = "1"
cid = "0.8.4"
libipld = "0.14.0"
num_enum = "0.5.7"
prost = "0.11"
bytes = "1.1.0"
iroh-rpc-client = { path = "../iroh-rpc-client", default-features = false }
iroh-util = { path = "../iroh-util", default-features = false }
tokio = { version = "1", features = ["fs"] }
futures = "0.3.21"
tracing = "0.1.34"
async-trait = "0.1.53"
async-recursion = "1.0.0"
trust-dns-resolver = { version = "0.22.0", features = ["tokio-runtime"] }
iroh-metrics = { path = "../iroh-metrics", default-features = false, features = ["resolver", "gateway"] }
async-stream = "0.3.3"
fastmurmur3 = "0.1.2"
once_cell = "1.13.0"
tokio-util = { version = "0.7", features = ["io"] }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"] }
tempfile = "3.3.0"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "fs"] }
iroh-store = { path = "../iroh-store", default-features = false }
iroh-rpc-types = { path = "../iroh-rpc-types", default-features = false }
iroh-car = { path = "../iroh-car" }
rand = "0.8.5"
rand_chacha = "0.3.1"
proptest = "1.0.0"
ahash = "0.8.0"

[build-dependencies]
prost-build = "0.11.1"

[features]
default = ["rpc-grpc", "rpc-mem"]
rpc-grpc = ["iroh-rpc-client/grpc", "iroh-metrics/rpc-grpc", "iroh-rpc-types/grpc", "iroh-store/rpc-grpc"]
rpc-mem = ["iroh-rpc-client/mem", "iroh-rpc-types/mem", "iroh-store/rpc-mem"]

[[bench]]
name = "unixfs"
harness = false
